{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7df7cf36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Member Name: Dhyaneshwaran N\n",
      "Member ID: 800290\n",
      "Mobile Number: 6369017603\n",
      "Memebership Plan: 3500\n",
      "Number of Months: 5\n",
      "Number of Services Used: 5\n",
      "Membership Status: True\n",
      "Service Cost: [1000, 300, 320, 790, 580]\n",
      "After Append the New Item: [1000, 300, 320, 790, 580, 1000]\n",
      "After inserting Service Cost: [1000, 300, 300, 320, 790, 580, 1000]\n",
      "After removing Registration Charge: [300, 300, 320, 790, 580, 1000]\n",
      "After Pop the item in the list: 320\n",
      "After Sorting the List: None\n",
      "Length of the Service Cost List: 5\n",
      "Maximum Item in the List: 1000\n",
      "Minimum Item in the List: 300\n",
      "Adding all the item in the List: 2970\n",
      "Cost_tuple: (300, 300, 580, 790, 1000, 350, 500, 790, 400, 500)\n",
      "First Service COst: 300\n",
      "Last Service Cost: 500\n",
      "First 3 Service Cost: (300, 300, 580)\n",
      "Last 2 Service Cost: (400, 500)\n",
      "Reverse Tuple: (500, 400, 790, 500, 350, 1000, 790, 580, 300, 300)\n",
      "Value: 300\n",
      "Value: 300\n",
      "Value: 580\n",
      "Value: 790\n",
      "Value: 1000\n",
      "Value: 350\n",
      "Value: 500\n",
      "Value: 790\n",
      "Value: 400\n",
      "Value: 500\n",
      "Member Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603}\n",
      "Member Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603, 'Total Cost': 2990}\n",
      "Member Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603, 'Total Cost': 2990, 'Average Service Cost': 250}\n",
      "Memeber Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603, 'Total Cost': 2990, 'Average Service Cost': 250, 'Highest Service Cost': 500}\n",
      "Member Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603, 'Total Cost': 2990, 'Average Service Cost': 250, 'Highest Service Cost': 500, 'Gym Name': 'Priyam'}\n",
      "Updated Member Details: {'Member Name': 'Dhyaneshwaran N', 'Member ID': 800290, 'Mobile Number': 6369017603, 'Total Cost': 2990, 'Average Service Cost': 250, 'Highest Service Cost': 500, 'Gym Name': 'Top Scale Fitness'}\n",
      "Keys: dict_keys(['Member Name', 'Member ID', 'Mobile Number', 'Total Cost', 'Average Service Cost', 'Highest Service Cost', 'Gym Name'])\n",
      "Values: dict_values(['Dhyaneshwaran N', 800290, 6369017603, 2990, 250, 500, 'Top Scale Fitness'])\n",
      "Items: dict_items([('Member Name', 'Dhyaneshwaran N'), ('Member ID', 800290), ('Mobile Number', 6369017603), ('Total Cost', 2990), ('Average Service Cost', 250), ('Highest Service Cost', 500), ('Gym Name', 'Top Scale Fitness')])\n",
      "Services 1\n",
      "Service: 3\n",
      "Benefit: 1\n",
      "Benefit: 1\n",
      "Benefit: 2\n",
      "Services 2\n",
      "Service: 2\n",
      "Benefit: 1\n",
      "Benefit: 2\n",
      "Services 3\n",
      "Service: 3\n",
      "Benefit: 1\n",
      "Benefit: 2\n",
      "Benefit: 3\n",
      "Services 4\n",
      "Service: 4\n",
      "Benefit: 1\n",
      "Benefit: 2\n",
      "Benefit: 3\n",
      "Benefit: 4\n",
      "Services 5\n",
      "Service: 5\n",
      "Benefit: 1\n",
      "Benefit: 2\n",
      "Benefit: 3\n",
      "Benefit: 4\n",
      "Benefit: 5\n",
      "GST: 538.2\n",
      "Final Amount: 3528.2\n",
      "Indexing: D\n",
      "Concatenation: Dhyaneshwaran NTrue\n",
      "Replication: Dhyaneshwaran NDhyaneshwaran N\n",
      "Membership Operator: False\n",
      "Unit Digit: 0\n",
      "Relational Operator: True\n",
      "Logical Operator: 5\n",
      "Bitwise Operator: 5\n",
      "Number_of_Months_in_Words: Three\n",
      "Swapping: 5 5\n",
      "Premium Member\n",
      "Free Personal Training Session\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# GYM MEMBERSHIP MANAGEMENT SYSTEM\n",
    "# Developed using Python\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 55)\n",
    "print(\"          GYM MEMBERSHIP MANAGEMENT SYSTEM\")\n",
    "print(\"=\" * 55)\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 1. MEMBER DETAILS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Member_Name = input(\"Enter Member Name: \")\n",
    "Member_ID = int(input(\"Enter Member ID: \"))\n",
    "Mobile_Number = input(\"Enter Mobile Number: \")\n",
    "Membership_Plan = input(\"Enter Membership Plan (Basic/Gold/Premium): \")\n",
    "Number_of_Months = int(input(\"Enter Number of Months: \"))\n",
    "Number_of_services_used = int(input(\"Enter Number of Services Used: \"))\n",
    "Membership_Status = input(\"Enter Membership Status (Active/Inactive): \")\n",
    "\n",
    "print(\"\\n--- MEMBER INFORMATION ---\")\n",
    "print(\"Member Name       :\", Member_Name)\n",
    "print(\"Member ID         :\", Member_ID)\n",
    "print(\"Mobile Number     :\", Mobile_Number)\n",
    "print(\"Membership Plan   :\", Membership_Plan)\n",
    "print(\"Number of Months  :\", Number_of_Months)\n",
    "print(\"Services Used     :\", Number_of_services_used)\n",
    "print(\"Membership Status :\", Membership_Status)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 2. SERVICE COST MANAGEMENT USING LIST\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Service_Cost = []\n",
    "Total = 0\n",
    "\n",
    "print(\"\\n--- ENTER SERVICE COSTS ---\")\n",
    "\n",
    "for i in range(Number_of_services_used):\n",
    "\n",
    "    Cost = float(input(f\"Enter Cost of Service {i + 1}: ₹\"))\n",
    "\n",
    "    # Prevent negative service cost\n",
    "    while Cost < 0:\n",
    "        print(\"Service cost cannot be negative.\")\n",
    "        Cost = float(input(\"Enter Service Cost Again: ₹\"))\n",
    "\n",
    "    Service_Cost.append(Cost)\n",
    "    Total += Cost\n",
    "\n",
    "\n",
    "print(\"\\nService Costs:\", Service_Cost)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 3. LIST OPERATIONS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "if Service_Cost:\n",
    "\n",
    "    print(\"\\n--- SERVICE COST SUMMARY ---\")\n",
    "\n",
    "    Service_Cost.sort()\n",
    "\n",
    "    print(\"Sorted Service Costs :\", Service_Cost)\n",
    "    print(\"Number of Services   :\", len(Service_Cost))\n",
    "    print(\"Highest Service Cost : ₹\", max(Service_Cost))\n",
    "    print(\"Lowest Service Cost  : ₹\", min(Service_Cost))\n",
    "    print(\"Total Service Cost   : ₹\", sum(Service_Cost))\n",
    "\n",
    "else:\n",
    "\n",
    "    print(\"\\nNo services were added.\")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 4. OPTIONAL ADDITIONAL SERVICES\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Additional_Services = int(\n",
    "    input(\"\\nEnter Number of Additional Services (0 if none): \")\n",
    ")\n",
    "\n",
    "for i in range(Additional_Services):\n",
    "\n",
    "    print(f\"\\nAdditional Service {i + 1}\")\n",
    "\n",
    "    Cost_1 = float(\n",
    "        input(\"Enter Service Cost (0 = Skip, 9999 = Stop): ₹\")\n",
    "    )\n",
    "\n",
    "    while Cost_1 < 0:\n",
    "        print(\"Negative cost is not allowed.\")\n",
    "        Cost_1 = float(input(\"Enter Cost Again: ₹\"))\n",
    "\n",
    "    if Cost_1 == 0:\n",
    "        print(\"Service Skipped\")\n",
    "        continue\n",
    "\n",
    "    if Cost_1 == 9999:\n",
    "        print(\"Additional Service Entry Stopped\")\n",
    "        break\n",
    "\n",
    "    Service_Cost.append(Cost_1)\n",
    "    Total += Cost_1\n",
    "\n",
    "\n",
    "print(\"\\nUpdated Service Costs:\", Service_Cost)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 5. TUPLE OPERATIONS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Cost_Tuple = tuple(Service_Cost)\n",
    "\n",
    "print(\"\\n--- SERVICE COST HISTORY ---\")\n",
    "print(\"Cost Tuple:\", Cost_Tuple)\n",
    "\n",
    "if Cost_Tuple:\n",
    "\n",
    "    print(\"First Service Cost :\", Cost_Tuple[0])\n",
    "    print(\"Last Service Cost  :\", Cost_Tuple[-1])\n",
    "    print(\"First 3 Costs      :\", Cost_Tuple[:3])\n",
    "    print(\"Last 2 Costs       :\", Cost_Tuple[-2:])\n",
    "    print(\"Reversed Costs     :\", Cost_Tuple[::-1])\n",
    "\n",
    "    print(\"\\nIndividual Service Costs:\")\n",
    "\n",
    "    for i in range(len(Cost_Tuple)):\n",
    "        print(f\"Service {i + 1}: ₹{Cost_Tuple[i]}\")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 6. MEMBER DETAILS USING DICTIONARY\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Member_Details = {\n",
    "    \"Member Name\": Member_Name,\n",
    "    \"Member ID\": Member_ID,\n",
    "    \"Mobile Number\": Mobile_Number,\n",
    "    \"Membership Plan\": Membership_Plan,\n",
    "    \"Membership Status\": Membership_Status,\n",
    "    \"Number of Months\": Number_of_Months\n",
    "}\n",
    "\n",
    "Member_Details[\"Total Service Cost\"] = Total\n",
    "\n",
    "if len(Service_Cost) > 0:\n",
    "\n",
    "    Member_Details[\"Average Service Cost\"] = (\n",
    "        Total / len(Service_Cost)\n",
    "    )\n",
    "\n",
    "    Member_Details[\"Highest Service Cost\"] = max(Service_Cost)\n",
    "\n",
    "else:\n",
    "\n",
    "    Member_Details[\"Average Service Cost\"] = 0\n",
    "    Member_Details[\"Highest Service Cost\"] = 0\n",
    "\n",
    "\n",
    "Gym_Name = input(\"\\nEnter Gym Name: \")\n",
    "\n",
    "Member_Details[\"Gym Name\"] = Gym_Name\n",
    "\n",
    "\n",
    "print(\"\\n--- MEMBER DETAILS ---\")\n",
    "\n",
    "for Key, Value in Member_Details.items():\n",
    "    print(f\"{Key}: {Value}\")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 7. DICTIONARY OPERATIONS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\nDictionary Keys:\")\n",
    "print(Member_Details.keys())\n",
    "\n",
    "print(\"\\nDictionary Values:\")\n",
    "print(Member_Details.values())\n",
    "\n",
    "print(\"\\nDictionary Items:\")\n",
    "print(Member_Details.items())\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 8. SERVICE BENEFITS - NESTED LOOP\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Number_of_Benefit_Services = int(\n",
    "    input(\"\\nEnter Number of Services to Add Benefits For: \")\n",
    ")\n",
    "\n",
    "for i in range(Number_of_Benefit_Services):\n",
    "\n",
    "    print(f\"\\nService {i + 1}\")\n",
    "\n",
    "    Number_of_Benefits = int(\n",
    "        input(\"Enter Number of Benefits: \")\n",
    "    )\n",
    "\n",
    "    for j in range(Number_of_Benefits):\n",
    "\n",
    "        Benefit = input(\n",
    "            f\"Enter Benefit {j + 1}: \"\n",
    "        )\n",
    "\n",
    "        print(\"Benefit Added:\", Benefit)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 9. BILL CALCULATION\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "Registration_Charge = 1000\n",
    "\n",
    "Total_Cost = Total + Registration_Charge\n",
    "\n",
    "print(\"\\n--- BILL CALCULATION ---\")\n",
    "\n",
    "print(\"Service Cost        : ₹\", Total)\n",
    "print(\"Registration Charge : ₹\", Registration_Charge)\n",
    "print(\"Subtotal            : ₹\", Total_Cost)\n",
    "\n",
    "\n",
    "# Discount Calculation\n",
    "\n",
    "Discount = 0\n",
    "\n",
    "if Total_Cost > 3000:\n",
    "\n",
    "    Discount = 1000\n",
    "    print(\"Discount Applied    : ₹\", Discount)\n",
    "\n",
    "\n",
    "Discounted_Amount = Total_Cost - Discount\n",
    "\n",
    "\n",
    "# GST after discount\n",
    "\n",
    "GST = Discounted_Amount * 18 / 100\n",
    "\n",
    "Final_Amount = Discounted_Amount + GST\n",
    "\n",
    "\n",
    "print(\"Amount After Discount: ₹\", round(Discounted_Amount, 2))\n",
    "print(\"GST (18%)            : ₹\", round(GST, 2))\n",
    "print(\"Final Amount         : ₹\", round(Final_Amount, 2))\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 10. STRING OPERATIONS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\n--- STRING OPERATIONS ---\")\n",
    "\n",
    "if Member_Name:\n",
    "\n",
    "    Indexing = Member_Name[0]\n",
    "    print(\"First Character:\", Indexing)\n",
    "\n",
    "\n",
    "Concatenation = Member_Name + \" - \" + Membership_Status\n",
    "print(\"Concatenation:\", Concatenation)\n",
    "\n",
    "Replication = Member_Name * 2\n",
    "print(\"Replication:\", Replication)\n",
    "\n",
    "Membership_Operator = \"a\" in Member_Name.lower()\n",
    "print(\"Does Name Contain 'a'?:\", Membership_Operator)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 11. PYTHON OPERATORS\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\n--- OPERATOR DEMONSTRATION ---\")\n",
    "\n",
    "Unit_Digit = Member_ID % 10\n",
    "print(\"Last Digit of Member ID:\", Unit_Digit)\n",
    "\n",
    "\n",
    "Statement_1 = Number_of_Months\n",
    "Statement_2 = Number_of_services_used\n",
    "\n",
    "\n",
    "# Relational Operator\n",
    "\n",
    "print(\n",
    "    \"Months >= Services:\",\n",
    "    Statement_1 >= Statement_2\n",
    ")\n",
    "\n",
    "\n",
    "# Logical Operator\n",
    "\n",
    "print(\n",
    "    \"Eligible Based on Duration & Services:\",\n",
    "    Statement_1 >= 3 and Statement_2 >= 2\n",
    ")\n",
    "\n",
    "\n",
    "# Bitwise Operator - included to demonstrate Python bitwise operation\n",
    "\n",
    "print(\n",
    "    \"Bitwise OR Result:\",\n",
    "    Statement_1 | Statement_2\n",
    ")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 12. VARIABLE SWAPPING\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "a = Number_of_Months\n",
    "b = Number_of_services_used\n",
    "\n",
    "a, b = b, a\n",
    "\n",
    "print(\"\\n--- VARIABLE SWAPPING ---\")\n",
    "print(\"After Swapping:\", a, b)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 13. MEMBERSHIP CATEGORY\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\n--- MEMBERSHIP CATEGORY ---\")\n",
    "\n",
    "if Final_Amount >= 3500:\n",
    "\n",
    "    Member_Category = \"Premium Member\"\n",
    "\n",
    "elif Final_Amount >= 2500:\n",
    "\n",
    "    Member_Category = \"Gold Member\"\n",
    "\n",
    "else:\n",
    "\n",
    "    Member_Category = \"Basic Member\"\n",
    "\n",
    "\n",
    "print(\"Member Category:\", Member_Category)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 14. MEMBERSHIP BENEFIT ELIGIBILITY\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\n--- BENEFIT ELIGIBILITY ---\")\n",
    "\n",
    "if Membership_Status.lower() == \"active\":\n",
    "\n",
    "    if Final_Amount >= 3500:\n",
    "\n",
    "        if Number_of_Months >= 3:\n",
    "\n",
    "            print(\n",
    "                \"Eligible for Free Personal Training Session\"\n",
    "            )\n",
    "\n",
    "        else:\n",
    "\n",
    "            print(\n",
    "                \"Complete at least 3 months to receive \"\n",
    "                \"the training benefit.\"\n",
    "            )\n",
    "\n",
    "    else:\n",
    "\n",
    "        print(\n",
    "            \"Premium spending criteria not met.\"\n",
    "        )\n",
    "\n",
    "else:\n",
    "\n",
    "    print(\n",
    "        \"Membership is inactive. Benefits are unavailable.\"\n",
    "    )\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 15. FINAL SUMMARY\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "print(\"\\n\" + \"=\" * 55)\n",
    "print(\"                 FINAL MEMBER SUMMARY\")\n",
    "print(\"=\" * 55)\n",
    "\n",
    "print(\"Gym Name          :\", Gym_Name)\n",
    "print(\"Member Name       :\", Member_Name)\n",
    "print(\"Member ID         :\", Member_ID)\n",
    "print(\"Membership Plan   :\", Membership_Plan)\n",
    "print(\"Membership Status :\", Membership_Status)\n",
    "print(\"Membership Period :\", Number_of_Months, \"Months\")\n",
    "print(\"Total Services    :\", len(Service_Cost))\n",
    "print(\"Service Cost      : ₹\", round(Total, 2))\n",
    "print(\"Discount          : ₹\", round(Discount, 2))\n",
    "print(\"GST               : ₹\", round(GST, 2))\n",
    "print(\"Final Amount      : ₹\", round(Final_Amount, 2))\n",
    "print(\"Member Category   :\", Member_Category)\n",
    "\n",
    "print(\"=\" * 55)\n",
    "print(\"          THANK YOU FOR USING THE SYSTEM\")\n",
    "print(\"=\" * 55)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0307cb7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
